[package]
name = "wasi-command-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.3", features = [ "abi3-py311" ] }

[build-dependencies]
flate2 = "1.0.26"
reqwest = { version = "0.11.18", features = ["blocking"] }
tar = "0.4.38"
bytes = "1.4.0"