[package]
name = "wlr-assets"
version = "0.2.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "rustls-tls"] }
tar = "0.4.40"
bytes = "1.5.0"
path-absolutize = "3.1.1"
