name: Build Ruby
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - "*"
  pull_request:
jobs:
  build-ruby:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.2.0
            target_version: 3_2_0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Ruby
        run: make ruby/v${{ matrix.target_version }}
      - name: Rename artifacts
        shell: bash
        run: |
          sudo mv ruby/build-output/ruby/v${{ matrix.target_version }}/bin/ruby{,-${{ matrix.version }}}.wasm
      - name: Upload ruby-${{ matrix.version }}.wasm artifact
        uses: actions/upload-artifact@v3
        with:
          name: ruby-${{ matrix.version }}.wasm
          path: ruby/build-output/ruby/v${{ matrix.target_version }}/bin/ruby-${{ matrix.version }}.wasm
          if-no-files-found: error
